//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/7 18:42
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace DMSF.Entity.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Adm_GroupUserRight", PrimaryKey = "GroupRightID")]
    public class Adm_GroupUserRight : BaseEntity
    {

        #region Private Properties

        private int? _groupRightID;//
        private int? _userGroupID;//
        private int? _rightID;//
        private int? _userGroupType;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GroupRightID", AutoIncrement = true)]
        public int? GroupRightID
        {
            get { return _groupRightID; }
            set { this.OnBasePropertyChanged<int?>("GroupRightID", value, ref _groupRightID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserGroupID")]
        public int? UserGroupID
        {
            get { return _userGroupID; }
            set { this.OnBasePropertyChanged<int?>("UserGroupID", value, ref _userGroupID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "RightID")]
        public int? RightID
        {
            get { return _rightID; }
            set { this.OnBasePropertyChanged<int?>("RightID", value, ref _rightID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserGroupType")]
        public int? UserGroupType
        {
            get { return _userGroupType; }
            set { this.OnBasePropertyChanged<int?>("UserGroupType", value, ref _userGroupType); }
        }

        #endregion

    }
}


