//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/8 10:22
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace DMSF.Entity.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Adm_OperationLog", PrimaryKey = "OperID")]
    public class Sys_AdminOperationLog : BaseEntity
    {

        #region Private Properties

        private long? _operID;//
        private int? _userID;//
        private string _userName;//
        private string _pageName;//
        private string _actionName;//
        private string _localIP;//
        private string _localAddr;//
        private string _url;//
        private int? _operationType;//
        private DateTime? _createTime;//
        private string _remark;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "OperID", AutoIncrement = true)]
        public long? OperID
        {
            get { return _operID; }
            set { this.OnBasePropertyChanged<long?>("OperID", value, ref _operID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserID")]
        public int? UserID
        {
            get { return _userID; }
            set { this.OnBasePropertyChanged<int?>("UserID", value, ref _userID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserName")]
        public string UserName
        {
            get { return _userName; }
            set { this.OnBasePropertyChanged("UserName", 64, value, ref _userName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "PageName")]
        public string PageName
        {
            get { return _pageName; }
            set { this.OnBasePropertyChanged("PageName", 200, value, ref _pageName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "ActionName")]
        public string ActionName
        {
            get { return _actionName; }
            set { this.OnBasePropertyChanged("ActionName", 100, value, ref _actionName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LocalIP")]
        public string LocalIP
        {
            get { return _localIP; }
            set { this.OnBasePropertyChanged("LocalIP", 64, value, ref _localIP); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LocalAddr")]
        public string LocalAddr
        {
            get { return _localAddr; }
            set { this.OnBasePropertyChanged("LocalAddr", 512, value, ref _localAddr); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "Url")]
        public string Url
        {
            get { return _url; }
            set { this.OnBasePropertyChanged("Url", 200, value, ref _url); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "OperationType")]
        public int? OperationType
        {
            get { return _operationType; }
            set { this.OnBasePropertyChanged<int?>("OperationType", value, ref _operationType); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "CreateTime")]
        public DateTime? CreateTime
        {
            get { return _createTime; }
            set { this.OnBasePropertyChanged<DateTime?>("CreateTime", value, ref _createTime); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "Remark")]
        public string Remark
        {
            get { return _remark; }
            set { this.OnBasePropertyChanged("Remark", 500, value, ref _remark); }
        }

        #endregion

    }
}


