//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/7 18:42
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace DMSF.Entity.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Adm_GroupUser", PrimaryKey = "GroupUserID")]
    public class Adm_GroupUser : BaseEntity
    {

        #region Private Properties

        private int? _groupUserID;//
        private int? _groupID;//
        private int? _userID;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GroupUserID", AutoIncrement = true)]
        public int? GroupUserID
        {
            get { return _groupUserID; }
            set { this.OnBasePropertyChanged<int?>("GroupUserID", value, ref _groupUserID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GroupID")]
        public int? GroupID
        {
            get { return _groupID; }
            set { this.OnBasePropertyChanged<int?>("GroupID", value, ref _groupID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserID")]
        public int? UserID
        {
            get { return _userID; }
            set { this.OnBasePropertyChanged<int?>("UserID", value, ref _userID); }
        }

        #endregion

    }
}


