//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/7 18:41
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace WDNET.Entity.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Adm_Rights", PrimaryKey = "RightsID")]
    public class Adm_Rights : BaseEntity
    {

        #region Private Properties

        private int? _rightsID;//
        private string _rightsName;//
        private int? _rightsParentID;//
        private string _displayName;//
        private int? _menuType;//
        private string _menuPath;//
        private int? _menuID;//
        private string _uRLName;//
        private string _uRLAddr;//
        private int? _statusFalg;//
        private int? _orderFlag;//
        private bool? _menuFlag;//
        private string _rightMemo;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "RightsID", AutoIncrement = true)]
        public int? RightsID
        {
            get { return _rightsID; }
            set { this.OnBasePropertyChanged<int?>("RightsID", value, ref _rightsID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "RightsName")]
        public string RightsName
        {
            get { return _rightsName; }
            set { this.OnBasePropertyChanged("RightsName", 100, value, ref _rightsName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "RightsParentID")]
        public int? RightsParentID
        {
            get { return _rightsParentID; }
            set { this.OnBasePropertyChanged<int?>("RightsParentID", value, ref _rightsParentID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "DisplayName")]
        public string DisplayName
        {
            get { return _displayName; }
            set { this.OnBasePropertyChanged("DisplayName", 50, value, ref _displayName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "MenuType")]
        public int? MenuType
        {
            get { return _menuType; }
            set { this.OnBasePropertyChanged<int?>("MenuType", value, ref _menuType); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "MenuPath")]
        public string MenuPath
        {
            get { return _menuPath; }
            set { this.OnBasePropertyChanged("MenuPath", 100, value, ref _menuPath); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "MenuID")]
        public int? MenuID
        {
            get { return _menuID; }
            set { this.OnBasePropertyChanged<int?>("MenuID", value, ref _menuID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "URLName")]
        public string URLName
        {
            get { return _uRLName; }
            set { this.OnBasePropertyChanged("URLName", 100, value, ref _uRLName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "URLAddr")]
        public string URLAddr
        {
            get { return _uRLAddr; }
            set { this.OnBasePropertyChanged("URLAddr", 500, value, ref _uRLAddr); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "StatusFalg")]
        public int? StatusFalg
        {
            get { return _statusFalg; }
            set { this.OnBasePropertyChanged<int?>("StatusFalg", value, ref _statusFalg); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "OrderFlag")]
        public int? OrderFlag
        {
            get { return _orderFlag; }
            set { this.OnBasePropertyChanged<int?>("OrderFlag", value, ref _orderFlag); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "MenuFlag")]
        public bool? MenuFlag
        {
            get { return _menuFlag; }
            set { this.OnBasePropertyChanged<bool?>("MenuFlag", value, ref _menuFlag); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "RightMemo")]
        public string RightMemo
        {
            get { return _rightMemo; }
            set { this.OnBasePropertyChanged("RightMemo", 500, value, ref _rightMemo); }
        }

        #endregion

    }
}

