//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/8 11:17
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using DMS.Commonfx.Model.Param;
using DMSF.Entity.DBEntity;
using DMSFrame;
using System.Collections.Generic;
using System.Linq;

namespace DMSF.BizLogic
{
    /// <summary>
    ///  处理层
    /// </summary>
    public class Adm_GroupBLL : BaseBLL<Adm_Group>
    {
        #region 增删改查
        /// <summary>
        /// 添加实体
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public override bool Insert(Adm_Group entity)
        {
            return base.Insert(entity);
        }

        /// <summary>
        /// 更新实体
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public bool Update(Adm_Group entity)
        {
            return base.Update(entity, q => q.GroupID == entity.GroupID);
        }

        /// <summary>
        /// 删除对象
        /// </summary>
        /// <param name="groupID"></param>
        /// <param name="userID"></param>
        /// <returns></returns>
        //public bool Del(DelParam param)
        //{
        //    Adm_Group entity = new Adm_Group();
        //    return base.Del(item =>
        //    {
        //        item.DeleteFlag = param.DeleteFlag;
        //        item.DeleteTime = DateTime.Now;
        //        return item;
        //    }, q => q.GroupID == param.ID);

        //}

        /// <summary>
        /// 获取实体
        /// </summary>
        /// <param name="groupID"></param>
        /// <returns></returns>
        public Adm_Group GetEntity(int? groupID)
        {
            return base.GetEntity(q => q.GroupID == groupID && q.DeleteFlag == false);
        }

        /// <summary>
        /// 分页查询
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public ConditionResult<Adm_Group> GetPageList(PageParam entity)
        {
            return base.GetPageList(entity, q => q.OrderBy(q.CreateTime.Desc()), where =>
            {
                where.And(q => q.DeleteFlag == false);
            });
        }

        #endregion

        #region 其他方法
        public List<Adm_Group> GetList()
        {
            List<Adm_Group> list = DMS.Create<Adm_Group>()
                .Where(q => q.StatusFlag == EnumStatusFlag.Passed && q.DeleteFlag == false)
                .OrderBy(q => q.OrderBy(q.GroupParentID))
                .Select(q => q.Columns(q.GroupID, q.GroupName, q.StatusFlag, q.GroupParentID))
                .ToList();
            List<Adm_Group> resultList = new List<Adm_Group>();
            PushList(0, list, 0, ref resultList);
            return resultList;
        }


        public void PushList(int? GroupParentID, List<Adm_Group> list, int level, ref List<Adm_Group> resultList)
        {
            List<Adm_Group> parentList = list.Where(q => q.GroupParentID == GroupParentID).ToList();
            foreach (Adm_Group item in parentList)
            {
                item.GroupName = formatLevel(level) + item.GroupName;
                resultList.Add(item);
                PushList(item.GroupID, list, level + 1, ref resultList);
            }
        }

        public string formatLevel(int level)
        {
            if (level == 0)
                return string.Empty;
            string result = string.Empty;
            for (int i = 0; i < level; i++)
            {
                result += "&nbsp;&nbsp;";
            }
            result = result + "|-";
            return result;
        }

        public bool ExistsDept(string GroupName)
        {
            return DMS.Create<Adm_Group>().Where(q => q.GroupName == GroupName && q.DeleteFlag == false).ToList().Count > 0;
        }
        #endregion
    }
}

