//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2017/11/21 18:39
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace WDNET.Entity.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Sys_Log", PrimaryKey = "LogID")]
    public class Sys_Log : BaseEntity
    {

        #region Private Properties

        private string _memberName;//用户
        private int? _logID;//
        private int? _subSysID;//子系统ID
        private string _subSysName;//子系统名称
        private string _iP;//IP
        private string _url;//来源地址
        private string _thread;//线程
        private string _level;//日志等级
        private string _logger;//记录日志的相关应用程序标识
        private string _message;//日志描述
        private int? _logType;//日志类型
        private string _exception;//异常信息
        private bool? _deleteFlag;//中否删除
        private DateTime? _createTime;//创建时间

        #endregion

        #region Public Properties

        /// <summary>
        /// 用户.
        /// </summary>
        [ColumnMapping(Name = "MemberName")]
        public string MemberName
        {
            get { return _memberName; }
            set { this.OnBasePropertyChanged("MemberName", 64, value, ref _memberName); }
        }
        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LogID", AutoIncrement = true)]
        public int? LogID
        {
            get { return _logID; }
            set { this.OnBasePropertyChanged<int?>("LogID", value, ref _logID); }
        }

        /// <summary>
        /// 子系统ID.
        /// </summary>
        [ColumnMapping(Name = "SubSysID")]
        public int? SubSysID
        {
            get { return _subSysID; }
            set { this.OnBasePropertyChanged<int?>("SubSysID", value, ref _subSysID); }
        }

        /// <summary>
        /// 子系统名称.
        /// </summary>
        [ColumnMapping(Name = "SubSysName")]
        public string SubSysName
        {
            get { return _subSysName; }
            set { this.OnBasePropertyChanged("SubSysName", 256, value, ref _subSysName); }
        }

        /// <summary>
        /// IP.
        /// </summary>
        [ColumnMapping(Name = "IP")]
        public string IP
        {
            get { return _iP; }
            set { this.OnBasePropertyChanged("IP", 32, value, ref _iP); }
        }

        /// <summary>
        /// 来源地址.
        /// </summary>
        [ColumnMapping(Name = "Url")]
        public string Url
        {
            get { return _url; }
            set { this.OnBasePropertyChanged("Url", 256, value, ref _url); }
        }

        /// <summary>
        /// 线程.
        /// </summary>
        [ColumnMapping(Name = "Thread")]
        public string Thread
        {
            get { return _thread; }
            set { this.OnBasePropertyChanged("Thread", 128, value, ref _thread); }
        }

        /// <summary>
        /// 日志等级.
        /// </summary>
        [ColumnMapping(Name = "Level")]
        public string Level
        {
            get { return _level; }
            set { this.OnBasePropertyChanged("Level", 128, value, ref _level); }
        }

        /// <summary>
        /// 记录日志的相关应用程序标识.
        /// </summary>
        [ColumnMapping(Name = "Logger")]
        public string Logger
        {
            get { return _logger; }
            set { this.OnBasePropertyChanged("Logger", 512, value, ref _logger); }
        }

        /// <summary>
        /// 日志描述.
        /// </summary>
        [ColumnMapping(Name = "Message")]
        public string Message
        {
            get { return _message; }
            set { this.OnBasePropertyChanged("Message", 2048, value, ref _message); }
        }

        /// <summary>
        /// 日志类型.
        /// </summary>
        [ColumnMapping(Name = "LogType")]
        public int? LogType
        {
            get { return _logType; }
            set { this.OnBasePropertyChanged<int?>("LogType", value, ref _logType); }
        }

        /// <summary>
        /// 异常信息.
        /// </summary>
        [ColumnMapping(Name = "Exception")]
        public string Exception
        {
            get { return _exception; }
            set { this.OnBasePropertyChanged("Exception", 2048, value, ref _exception); }
        }

        /// <summary>
        /// 中否删除.
        /// </summary>
        [ColumnMapping(Name = "DeleteFlag"), Newtonsoft.Json.JsonIgnore]
        public bool? DeleteFlag
        {
            get { return _deleteFlag; }
            set { this.OnBasePropertyChanged<bool?>("DeleteFlag", value, ref _deleteFlag); }
        }

        /// <summary>
        /// 创建时间.
        /// </summary>
        [ColumnMapping(Name = "CreateTime")]
        public DateTime? CreateTime
        {
            get { return _createTime; }
            set { this.OnBasePropertyChanged<DateTime?>("CreateTime", value, ref _createTime); }
        }

        #endregion

    }
}

