//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2016/3/17 17:25
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace ConsoleAppTest.Model
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Sys_VisitLog", PrimaryKey = "VisitID", ConfigName = "CSTJRNET_STATISTICS")]
    public class Sys_VisitLog : BaseEntity
    {

        #region Private Properties

        private int? _visitID;//
        private DateTime? _visitDate;//浏览时间
        private string _visitKey;//
        private int? _userID;//登录ID
        private string _userName;//
        private string _visitIP;//浏览IP
        private string _visitDomain;//浏览域名
        private string _reaPath;//访问实际路径aspx
        private string _reaDescription;//访问实际路径说明(以实际来区分是搜索还是商品页面)
        private string _visitURL;//浏览地址
        private string _pageTitle;//浏览Title
        private string _referrer;//来源页面
        private string _customerResolution;//客户端分辨率
        private string _cusotmerColor;//客户端颜色
        private string _language;//客户端语言
        private string _platform;//操作系统
        private string _browser;//浏览器类型
        private string _browserID;//浏览器标识
        private string _browserVersion;//浏览器版本号
        private string _userAgent;//访问信息
        private string _account;//访问域
        private int? _stopTimes;//停留时长信息(秒)
        private string _shopName;//入驻供应商的ID信息
        private bool? _statisticsFlag;//
        private string _pageInfo;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "VisitID", AutoIncrement = true)]
        public int? VisitID
        {
            get { return _visitID; }
            set { this.OnBasePropertyChanged<int?>("VisitID", value, ref _visitID); }
        }

        /// <summary>
        /// 浏览时间.
        /// </summary>
        [ColumnMapping(Name = "VisitDate")]
        public DateTime? VisitDate
        {
            get { return _visitDate; }
            set { this.OnBasePropertyChanged<DateTime?>("VisitDate", value, ref _visitDate); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "VisitKey")]
        public string VisitKey
        {
            get { return _visitKey; }
            set { this.OnBasePropertyChanged("VisitKey", 64, value, ref _visitKey); }
        }

        /// <summary>
        /// 登录ID.
        /// </summary>
        [ColumnMapping(Name = "UserID")]
        public int? UserID
        {
            get { return _userID; }
            set { this.OnBasePropertyChanged<int?>("UserID", value, ref _userID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "UserName")]
        public string UserName
        {
            get { return _userName; }
            set { this.OnBasePropertyChanged("UserName", 64, value, ref _userName); }
        }

        /// <summary>
        /// 浏览IP.
        /// </summary>
        [ColumnMapping(Name = "VisitIP")]
        public string VisitIP
        {
            get { return _visitIP; }
            set { this.OnBasePropertyChanged("VisitIP", 32, value, ref _visitIP); }
        }

        /// <summary>
        /// 浏览域名.
        /// </summary>
        [ColumnMapping(Name = "VisitDomain")]
        public string VisitDomain
        {
            get { return _visitDomain; }
            set { this.OnBasePropertyChanged("VisitDomain", 64, value, ref _visitDomain); }
        }

        /// <summary>
        /// 访问实际路径aspx.
        /// </summary>
        [ColumnMapping(Name = "ReaPath")]
        public string ReaPath
        {
            get { return _reaPath; }
            set { this.OnBasePropertyChanged("ReaPath", 1024, value, ref _reaPath); }
        }

        /// <summary>
        /// 访问实际路径说明(以实际来区分是搜索还是商品页面).
        /// </summary>
        [ColumnMapping(Name = "ReaDescription")]
        public string ReaDescription
        {
            get { return _reaDescription; }
            set { this.OnBasePropertyChanged("ReaDescription", 64, value, ref _reaDescription); }
        }

        /// <summary>
        /// 浏览地址.
        /// </summary>
        [ColumnMapping(Name = "VisitURL")]
        public string VisitURL
        {
            get { return _visitURL; }
            set { this.OnBasePropertyChanged("VisitURL", 1024, value, ref _visitURL); }
        }

        /// <summary>
        /// 浏览Title.
        /// </summary>
        [ColumnMapping(Name = "PageTitle")]
        public string PageTitle
        {
            get { return _pageTitle; }
            set { this.OnBasePropertyChanged("PageTitle", 512, value, ref _pageTitle); }
        }

        /// <summary>
        /// 来源页面.
        /// </summary>
        [ColumnMapping(Name = "Referrer")]
        public string Referrer
        {
            get { return _referrer; }
            set { this.OnBasePropertyChanged("Referrer", 1024, value, ref _referrer); }
        }

        /// <summary>
        /// 客户端分辨率.
        /// </summary>
        [ColumnMapping(Name = "CustomerResolution")]
        public string CustomerResolution
        {
            get { return _customerResolution; }
            set { this.OnBasePropertyChanged("CustomerResolution", 64, value, ref _customerResolution); }
        }

        /// <summary>
        /// 客户端颜色.
        /// </summary>
        [ColumnMapping(Name = "CusotmerColor")]
        public string CusotmerColor
        {
            get { return _cusotmerColor; }
            set { this.OnBasePropertyChanged("CusotmerColor", 64, value, ref _cusotmerColor); }
        }

        /// <summary>
        /// 客户端语言.
        /// </summary>
        [ColumnMapping(Name = "Language")]
        public string Language
        {
            get { return _language; }
            set { this.OnBasePropertyChanged("Language", 64, value, ref _language); }
        }

        /// <summary>
        /// 操作系统.
        /// </summary>
        [ColumnMapping(Name = "Platform")]
        public string Platform
        {
            get { return _platform; }
            set { this.OnBasePropertyChanged("Platform", 64, value, ref _platform); }
        }

        /// <summary>
        /// 浏览器类型.
        /// </summary>
        [ColumnMapping(Name = "Browser")]
        public string Browser
        {
            get { return _browser; }
            set { this.OnBasePropertyChanged("Browser", 64, value, ref _browser); }
        }

        /// <summary>
        /// 浏览器标识.
        /// </summary>
        [ColumnMapping(Name = "BrowserID")]
        public string BrowserID
        {
            get { return _browserID; }
            set { this.OnBasePropertyChanged("BrowserID", 64, value, ref _browserID); }
        }

        /// <summary>
        /// 浏览器版本号.
        /// </summary>
        [ColumnMapping(Name = "BrowserVersion")]
        public string BrowserVersion
        {
            get { return _browserVersion; }
            set { this.OnBasePropertyChanged("BrowserVersion", 64, value, ref _browserVersion); }
        }

        /// <summary>
        /// 访问信息.
        /// </summary>
        [ColumnMapping(Name = "UserAgent")]
        public string UserAgent
        {
            get { return _userAgent; }
            set { this.OnBasePropertyChanged("UserAgent", 512, value, ref _userAgent); }
        }

        /// <summary>
        /// 访问域.
        /// </summary>
        [ColumnMapping(Name = "Account")]
        public string Account
        {
            get { return _account; }
            set { this.OnBasePropertyChanged("Account", 64, value, ref _account); }
        }

        /// <summary>
        /// 停留时长信息(秒).
        /// </summary>
        [ColumnMapping(Name = "StopTimes")]
        public int? StopTimes
        {
            get { return _stopTimes; }
            set { this.OnBasePropertyChanged<int?>("StopTimes", value, ref _stopTimes); }
        }

        /// <summary>
        /// 入驻供应商的ID信息.
        /// </summary>
        [ColumnMapping(Name = "ShopName")]
        public string ShopName
        {
            get { return _shopName; }
            set { this.OnBasePropertyChanged("ShopName", 64, value, ref _shopName); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "StatisticsFlag")]
        public bool? StatisticsFlag
        {
            get { return _statisticsFlag; }
            set { this.OnBasePropertyChanged<bool?>("StatisticsFlag", value, ref _statisticsFlag); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "PageInfo")]
        public string PageInfo
        {
            get { return _pageInfo; }
            set { this.OnBasePropertyChanged("PageInfo", 1024, value, ref _pageInfo); }
        }

        #endregion

    }
}


