//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2021/11/8 15:29
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace DMSF.Entity
{
    /// <summary>
    /// 清标信息表
    /// </summary>
    [Serializable]
    [TableMapping(Name = "LIST_BASIC", PrimaryKey = "ID", ConfigName = "EVAL_DB")]
    public class LIST_BASIC : BaseEntity
    {

        #region Private Properties

        private int? _iD;//
        private Guid? _gID;//
        private string _tITLE;//
        private int? _lISTSTATE;//
        private string _dEVELOPER_CODE;//
        private string _dEVELOPER_TITLE;//
        private string _cUS_STRUCTURE_CODE;//
        private string _dEPARTMENT_CODE;//
        private string _cUS_DEPART_CODE;//
        private int? _pJT_BASIC_ID;//
        private string _pJT_BASIC_TITLE;//
        private string _lISTUNIT_CODE;//
        private string _lISTUNIT_TITLE;//
        private int? _lIST_INDIVIDUAL_ID;//
        private Guid? _gID_LIST_INDIVIDUAL;//
        private string _lIST_INDIVIDUAL_TITLE;//
        private int? _lIST_SECTION_ID;//
        private Guid? _gID_LIST_SECTION;//
        private string _sECTION;//
        private int? _lIST_TYPE_ID;//
        private string _lIST_TYPE_TITLE;//
        private int? _iFGRID;//
        private string _rEMARK;//
        private int? _iFUSED;//
        private DateTime? _iNDATE;//
        private int? _iNUSERID;//
        private decimal? _bUILDAREA;//建筑面积
        private int? _sORT;//排序字段

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "ID", AutoIncrement = true)]
        public int? ID
        {
            get { return _iD; }
            set { this.OnBasePropertyChanged<int?>("ID", value, ref _iD); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GID")]
        public Guid? GID
        {
            get { return _gID; }
            set { this.OnBasePropertyChanged<Guid?>("GID", value, ref _gID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "TITLE")]
        public string TITLE
        {
            get { return _tITLE; }
            set { this.OnBasePropertyChanged("TITLE", 100, value, ref _tITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LISTSTATE")]
        public int? LISTSTATE
        {
            get { return _lISTSTATE; }
            set { this.OnBasePropertyChanged<int?>("LISTSTATE", value, ref _lISTSTATE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "DEVELOPER_CODE")]
        public string DEVELOPER_CODE
        {
            get { return _dEVELOPER_CODE; }
            set { this.OnBasePropertyChanged("DEVELOPER_CODE", 20, value, ref _dEVELOPER_CODE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "DEVELOPER_TITLE")]
        public string DEVELOPER_TITLE
        {
            get { return _dEVELOPER_TITLE; }
            set { this.OnBasePropertyChanged("DEVELOPER_TITLE", 100, value, ref _dEVELOPER_TITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "CUS_STRUCTURE_CODE")]
        public string CUS_STRUCTURE_CODE
        {
            get { return _cUS_STRUCTURE_CODE; }
            set { this.OnBasePropertyChanged("CUS_STRUCTURE_CODE", 40, value, ref _cUS_STRUCTURE_CODE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "DEPARTMENT_CODE")]
        public string DEPARTMENT_CODE
        {
            get { return _dEPARTMENT_CODE; }
            set { this.OnBasePropertyChanged("DEPARTMENT_CODE", 20, value, ref _dEPARTMENT_CODE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "CUS_DEPART_CODE")]
        public string CUS_DEPART_CODE
        {
            get { return _cUS_DEPART_CODE; }
            set { this.OnBasePropertyChanged("CUS_DEPART_CODE", 20, value, ref _cUS_DEPART_CODE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "PJT_BASIC_ID")]
        public int? PJT_BASIC_ID
        {
            get { return _pJT_BASIC_ID; }
            set { this.OnBasePropertyChanged<int?>("PJT_BASIC_ID", value, ref _pJT_BASIC_ID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "PJT_BASIC_TITLE")]
        public string PJT_BASIC_TITLE
        {
            get { return _pJT_BASIC_TITLE; }
            set { this.OnBasePropertyChanged("PJT_BASIC_TITLE", 100, value, ref _pJT_BASIC_TITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LISTUNIT_CODE")]
        public string LISTUNIT_CODE
        {
            get { return _lISTUNIT_CODE; }
            set { this.OnBasePropertyChanged("LISTUNIT_CODE", 20, value, ref _lISTUNIT_CODE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LISTUNIT_TITLE")]
        public string LISTUNIT_TITLE
        {
            get { return _lISTUNIT_TITLE; }
            set { this.OnBasePropertyChanged("LISTUNIT_TITLE", 50, value, ref _lISTUNIT_TITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LIST_INDIVIDUAL_ID")]
        public int? LIST_INDIVIDUAL_ID
        {
            get { return _lIST_INDIVIDUAL_ID; }
            set { this.OnBasePropertyChanged<int?>("LIST_INDIVIDUAL_ID", value, ref _lIST_INDIVIDUAL_ID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GID_LIST_INDIVIDUAL")]
        public Guid? GID_LIST_INDIVIDUAL
        {
            get { return _gID_LIST_INDIVIDUAL; }
            set { this.OnBasePropertyChanged<Guid?>("GID_LIST_INDIVIDUAL", value, ref _gID_LIST_INDIVIDUAL); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LIST_INDIVIDUAL_TITLE")]
        public string LIST_INDIVIDUAL_TITLE
        {
            get { return _lIST_INDIVIDUAL_TITLE; }
            set { this.OnBasePropertyChanged("LIST_INDIVIDUAL_TITLE", 100, value, ref _lIST_INDIVIDUAL_TITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LIST_SECTION_ID")]
        public int? LIST_SECTION_ID
        {
            get { return _lIST_SECTION_ID; }
            set { this.OnBasePropertyChanged<int?>("LIST_SECTION_ID", value, ref _lIST_SECTION_ID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "GID_LIST_SECTION")]
        public Guid? GID_LIST_SECTION
        {
            get { return _gID_LIST_SECTION; }
            set { this.OnBasePropertyChanged<Guid?>("GID_LIST_SECTION", value, ref _gID_LIST_SECTION); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "SECTION")]
        public string SECTION
        {
            get { return _sECTION; }
            set { this.OnBasePropertyChanged("SECTION", 100, value, ref _sECTION); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LIST_TYPE_ID")]
        public int? LIST_TYPE_ID
        {
            get { return _lIST_TYPE_ID; }
            set { this.OnBasePropertyChanged<int?>("LIST_TYPE_ID", value, ref _lIST_TYPE_ID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "LIST_TYPE_TITLE")]
        public string LIST_TYPE_TITLE
        {
            get { return _lIST_TYPE_TITLE; }
            set { this.OnBasePropertyChanged("LIST_TYPE_TITLE", 100, value, ref _lIST_TYPE_TITLE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "IFGRID")]
        public int? IFGRID
        {
            get { return _iFGRID; }
            set { this.OnBasePropertyChanged<int?>("IFGRID", value, ref _iFGRID); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "REMARK")]
        public string REMARK
        {
            get { return _rEMARK; }
            set { this.OnBasePropertyChanged("REMARK", 200, value, ref _rEMARK); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "IFUSED")]
        public int? IFUSED
        {
            get { return _iFUSED; }
            set { this.OnBasePropertyChanged<int?>("IFUSED", value, ref _iFUSED); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "INDATE")]
        public DateTime? INDATE
        {
            get { return _iNDATE; }
            set { this.OnBasePropertyChanged<DateTime?>("INDATE", value, ref _iNDATE); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "INUSERID")]
        public int? INUSERID
        {
            get { return _iNUSERID; }
            set { this.OnBasePropertyChanged<int?>("INUSERID", value, ref _iNUSERID); }
        }

        /// <summary>
        /// 建筑面积.
        /// </summary>
        [ColumnMapping(Name = "BUILDAREA")]
        public decimal? BUILDAREA
        {
            get { return _bUILDAREA; }
            set { this.OnBasePropertyChanged<decimal?>("BUILDAREA", value, ref _bUILDAREA); }
        }

        /// <summary>
        /// 排序字段.
        /// </summary>
        [ColumnMapping(Name = "SORT")]
        public int? SORT
        {
            get { return _sORT; }
            set { this.OnBasePropertyChanged<int?>("SORT", value, ref _sORT); }
        }

        #endregion

    }
}


