//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2021/12/12 1:37
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;

/// <summary>
/// 
/// </summary>
namespace DMSF.Entity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "cms_news", PrimaryKey = "id", DMSDbType = DMSDbType.Mysql, ConfigName = "db_cms01")]
    public class cms_news : BaseEntity
    {
        #region Private Properties

        private long? _id;
        private string _title;
        private string _content;
        private DateTime? _create_time;

        #endregion

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "id", AutoIncrement = true)]
        public long? id
        {
            get
            {
                return _id;
            }
            set
            {
                object _oldvalue = _id;
                _id = value;

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("id", _oldvalue, _id);

                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "title")]
        public string title
        {
            get
            {
                return _title;
            }
            set
            {
                object _oldvalue = _title;
                _title = value.SubStr(765);

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("title", _oldvalue, _title);
                    this.OnMappingPropertyChanged("title", _oldvalue, _title);
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "content")]
        public string content
        {
            get
            {
                return _content;
            }
            set
            {
                object _oldvalue = _content;
                _content = value;

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("content", _oldvalue, _content);
                    this.OnMappingPropertyChanged("content", _oldvalue, _content);
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "create_time")]
        public DateTime? create_time
        {
            get
            {
                return _create_time;
            }
            set
            {
                object _oldvalue = _create_time;
                _create_time = value;

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("create_time", _oldvalue, _create_time);
                    this.OnMappingPropertyChanged("create_time", _oldvalue, _create_time);
                }
            }
        }

        #endregion
    }
}


