//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2021/12/12 1:35
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;

/// <summary>
/// 
/// </summary>
namespace DMSF.Entity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "cms_user", PrimaryKey = "id", DMSDbType = DMSDbType.Mysql, ConfigName = "db_cms01")]
    public class cms_user : BaseEntity
    {
        #region Private Properties

        private long? _id;
        private string _user_name;
        private string _user_password;
        private DateTime? _create_time;

        #endregion

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "id", AutoIncrement = true)]
        public long? id
        {
            get
            {
                return _id;
            }
            set
            {
                object _oldvalue = _id;
                _id = value;

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("id", _oldvalue, _id);

                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "user_name")]
        public string user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                object _oldvalue = _user_name;
                _user_name = value.SubStr(96);

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("user_name", _oldvalue, _user_name);
                    this.OnMappingPropertyChanged("user_name", _oldvalue, _user_name);
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "user_password")]
        public string user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                object _oldvalue = _user_password;
                _user_password = value.SubStr(765);

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("user_password", _oldvalue, _user_password);
                    this.OnMappingPropertyChanged("user_password", _oldvalue, _user_password);
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [ColumnMapping(Name = "create_time")]
        public DateTime? create_time
        {
            get
            {
                return _create_time;
            }
            set
            {
                object _oldvalue = _create_time;
                _create_time = value;

                if ((value == null) || (!value.Equals(_oldvalue)))
                {
                    this.OnPropertyChanged("create_time", _oldvalue, _create_time);
                    this.OnMappingPropertyChanged("create_time", _oldvalue, _create_time);
                }
            }
        }

        #endregion
    }
}


