//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2017/3/27 18:43
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace DMSFrame.Test.Model
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "Sys_SearchKey", PrimaryKey = "SearchID", ConfigName = "CSTJRNET_STATISTICS")]
    public class Sys_SearchKey : BaseEntity
    {

        #region Private Properties

        private int? _searchID;//主键
        private string _searchKey;//搜索关键词
        private int? _searchCount;////点击数量
        private DateTime? _lastUpdateTime;//最后点击时间
        private string _remark;//备注信息
        private bool? _isJoin;//是否已加入到solr字典
        private string _firstPageResult;//第一搜索结果

        #endregion

        #region Public Properties

        /// <summary>
        /// 主键.
        /// </summary>
        [ColumnMapping(Name = "SearchID", AutoIncrement = true)]
        public int? SearchID
        {
            get { return _searchID; }
            set { this.OnBasePropertyChanged<int?>("SearchID", value, ref _searchID); }
        }

        /// <summary>
        /// 搜索关键词.
        /// </summary>
        [ColumnMapping(Name = "SearchKey")]
        public string SearchKey
        {
            get { return _searchKey; }
            set { this.OnBasePropertyChanged("SearchKey", 128, value, ref _searchKey); }
        }

        /// <summary>
        /// //点击数量.
        /// </summary>
        [ColumnMapping(Name = "SearchCount")]
        public int? SearchCount
        {
            get { return _searchCount; }
            set { this.OnBasePropertyChanged<int?>("SearchCount", value, ref _searchCount); }
        }

        /// <summary>
        /// 最后点击时间.
        /// </summary>
        [ColumnMapping(Name = "LastUpdateTime")]
        public DateTime? LastUpdateTime
        {
            get { return _lastUpdateTime; }
            set { this.OnBasePropertyChanged<DateTime?>("LastUpdateTime", value, ref _lastUpdateTime); }
        }

        /// <summary>
        /// 备注信息.
        /// </summary>
        [ColumnMapping(Name = "Remark")]
        public string Remark
        {
            get { return _remark; }
            set { this.OnBasePropertyChanged("Remark", 512, value, ref _remark); }
        }

        /// <summary>
        /// 是否已加入到solr字典.
        /// </summary>
        [ColumnMapping(Name = "IsJoin")]
        public bool? IsJoin
        {
            get { return _isJoin; }
            set { this.OnBasePropertyChanged<bool?>("IsJoin", value, ref _isJoin); }
        }

        /// <summary>
        /// 第一搜索结果.
        /// </summary>
        [ColumnMapping(Name = "FirstPageResult")]
        public string FirstPageResult
        {
            get { return _firstPageResult; }
            set { this.OnBasePropertyChanged("FirstPageResult", 1024, value, ref _firstPageResult); }
        }

        #endregion

    }
}


